### ISSUE TITLE
Installation lab

### ISSUE THREAD

**Issue by michal-sebesta** [michal-sebesta/SEBC#2]

**Comment by michal-sebesta** [comment]
leaving chronyd.service as NTP serviece >>> not installing/using NTP

**Comment by michal-sebesta** [comment]
I got this problem with alternative and you asked me to document:

```
problem parsing alternatives probably when openjdk installed on centos 7 system


cloudera agent log:

[08/Mar/2017 14:54:14 +0000] 2511 MainThread parcel       INFO     chmod: /opt/cloudera/parcels/CDH-5.8.3-1.cdh5.8.3.p0.2/etc/oozie/tomcat-conf.http.mr1/conf/ssl/ssl-server.xml 0750
[08/Mar/2017 14:54:14 +0000] 2511 MainThread parcel       INFO     Executing command ['chmod', '0750', u'/opt/cloudera/parcels/CDH-5.8.3-1.cdh5.8.3.p0.2/etc/oozie/tomcat-conf.http.mr1/conf/ssl
/ssl-server.xml']
[08/Mar/2017 14:54:14 +0000] 2511 MainThread parcel_cache INFO     Using /opt/cloudera/parcel-cache for parcel cache
[08/Mar/2017 14:54:14 +0000] 2511 MainThread agent        ERROR    Caught unexpected exception in main loop.
Traceback (most recent call last):
  File "/usr/lib64/cmf/agent/build/env/lib/python2.7/site-packages/cmf-5.10.0-py2.7.egg/cmf/agent.py", line 710, in __issue_heartbeat
    self._init_after_first_heartbeat_response(resp_data)
  File "/usr/lib64/cmf/agent/build/env/lib/python2.7/site-packages/cmf-5.10.0-py2.7.egg/cmf/agent.py", line 947, in _init_after_first_heartbeat_response
    self.client_configs.load()
  File "/usr/lib64/cmf/agent/build/env/lib/python2.7/site-packages/cmf-5.10.0-py2.7.egg/cmf/client_configs.py", line 682, in load
    new_deployed.update(self._lookup_alternatives(fname))
  File "/usr/lib64/cmf/agent/build/env/lib/python2.7/site-packages/cmf-5.10.0-py2.7.egg/cmf/client_configs.py", line 432, in _lookup_alternatives
    return self._parse_alternatives(alt_name, out)
  File "/usr/lib64/cmf/agent/build/env/lib/python2.7/site-packages/cmf-5.10.0-py2.7.egg/cmf/client_configs.py", line 444, in _parse_alternatives
    path, _, _, priority_str = line.rstrip().split(" ")






solution: (uninstall java or remove lines that is python script unable to parse )
https://community.cloudera.com/t5/Cloudera-Manager-Installation/Problem-with-cloudera-agent/td-p/47698
```

**Comment by mfernest** [comment]
Thanks for noting that. I'm not sure the last time I've seen that.

**C**ompleted.
